# -*- coding: utf-8 -*-
"""marvel_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DlikZtz2S3ZPvl_tU5K_QmDbaKkW6fTd
"""

!pip install requests pandas -q

import pandas as pd
import requests #para conversa com a internet (API MARVEL)
import hashlib #ferramenta de criptografia
import time
from datetime import datetime
import getpass #proteção do código com uma "senha"
from IPython.display import display

print("Bibliotecas carregadas")

class api_cliente:
  def __init__(self, public_key, private_key):
    self.public_key = public_key
    self.private_key = private_key
    self.base_url = 'https://gateway.marvel.com/v1/public/'

  def _params_(self):
    timestamp = str(int(time.time()))
    hash_str = timestamp + self.private_key + self.public_key
    hash_md5 = hashlib.md5(hash_str.encode()).hexdigest()

    return {
        'ts': timestamp,
        'apikey': self.public_key,
        'hash': hash_md5
        }

print("Classe criada")

# importação dos dados da API MARVEL

def get_characters(self, limit=100, offset=0):
  aut_params = self.aut_gerador_params()
  params = {
      **aut_params,
      limit: 'limit',
      offset: 'offset'
  }
  try:
    response = requests.get(f'{self.base_url} characters', params=params)
    response.status()
    return response.json()
  except requests.exceptions.RequestException as e:
    print(f"Erro :{e}")
    return None

  print("Classe criada")

def teste_conexao_api(self):
  limite = self.get_characters(limit=1)
  if limite and 'limit' in limite:
    print("Sucesso")
    return True

def obter_personagem_df(self, total_personagens=200, apresenta_progresso=True):
  personagens = []
  limit = 100
  if apresenta_progresso:
    print("Recebendo personagens")
    for offset in range(0, total_personagens, limit):
      response = self.get_characters(limit=limit, offset=offset)
      # if response in response
      if response and 'data' in response and 'results' in response['data']:
        characters = response['data']['result']
    for character in characters:
      dados_personagens = {
          'id': character['id'],
          'name': character['name'],
          'description': character['descricao'] if character['description'] else 'no description',
          'series': character['series', 'available'],
          'comics': character['comics', 'available'],
          'events': character['events', 'available'],
          'stories': character['stories', 'available']
      }